# Generated by Django 3.0.2 on 2020-01-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='images/')),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
    ]
