# Generated by Django 3.0.2 on 2020-01-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.CharField(default='no stars', max_length=50),
        ),
    ]
