# Generated by Django 2.0 on 2020-01-28 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_bigreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
